apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bondy-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: io2
  iopsPerGB: "1000"
  allowautoiopspergbincrease: "true"
  fsType: ext4