apiVersion: v1
kind: Service
metadata:
  name: external-wamp
  annotations:
    # overriding tcp protocol!!!
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-071f51aff6ca142ba,eipalloc-08130511ffb26f445
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:108876670047:certificate/97d59beb-1058-474b-9625-8c5c429634f4
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https,wamp-tls,bridge-tls"
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: None
spec:
  type: LoadBalancer
  selector:
    app: bondy
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: wamp-tls
      port: 9073
      targetPort: wamp-tls
    - name: bridge-tls
      port: 9075
      targetPort: bridge-tls
