apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ../../bases/bondy


patchesStrategicMerge:
- resources/bondy-statefulset-replicas-patch.yaml
- resources/bondy-statefulset-resources-patch.yaml
- resources/bondy-statefulset-volume-claim-patch.yaml
- resources/bondy-statefulset-volumes-patch.yaml
- resources/bondy-load-balancer-patch.yaml


configMapGenerator:
- name: bondy-config
  namespace: wamp
  files:
  - config/bondy.conf.template
  - config/security_config.json.template

generatorOptions:
  disableNameSuffixHash: true
