apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
  - ../../../../bases/wamp/bondy


patchesStrategicMerge:
- resources/bondy-statefulset-patch.yaml
- resources/bondy-load-balancer-patch.yaml
- resources/bondy-storage-class-patch.yaml


configMapGenerator:
- name: bondy-config
  namespace: wamp
  files:
  - config/bondy.conf.template
  - config/security_config.json.template
  - config/broker_bridge_config.json.template

generatorOptions:
  disableNameSuffixHash: true
