apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bondy
spec:
  selector:
    matchLabels:
      app: bondy
  serviceName: bondy
  template:
    metadata:
      labels:
        app: bondy
    spec:
      containers:
      - name: bondy
        volumeMounts:
          - name: bondy-ssl-volume
            readOnly: true
            mountPath: /bondy/etc/ssl
        resources:
          requests:
            memory: 1Gi
            cpu: "2"
          limits:
            memory: 4Gi
            cpu: "4"
      volumes:
        - name: bondy-ssl-volume
          secret:
            secretName: rsa-cert-2048-bondy